### ISSUE TITLE
Some readme would be nice

### ISSUE THREAD

**Issue by daniellienert** [fnkr/homebrew-public#1]
Hey @fnkr, 
please add some lines which tools will be provided and how the formula is tapped and installed.

Cheers,
Daniel

**Comment by fnkr** [comment]
Hi @daniellienert,

you can find documentation about how Homebrew repositories work in the official docs: https://docs.brew.sh/Taps (just do `brew install fnkr/public/<PACKAGE>`). Also each formula has a description and you can use `brew info fnkr/public/<PACKAGE>` to view it. This repository only serves as storage for Homebrew formula I create and use elsewhere. It is updated automatically once I push a change to the corresponding source repository of a formula.
